spring:
    datasource:
        url: jdbc:mysql://mysql01:3306/future
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
graphql:
    servlet:
        mapping: /graphql
        enabled: true
        corsEnabled: true
graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    pageTitle: GraphiQL
        