package xyz.ucwork.future.domain.model;

public class Members {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.id
     *
     * @return the value of members.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.id
     *
     * @param id the value for members.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members.name
     *
     * @return the value of members.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members.name
     *
     * @param name the value for members.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }
}